### ISSUE TITLE
pandoc fails to load googleapi 

### ISSUE THREAD

**Issue by jdforest** [GerkeLab/betterposter#4]
When I tried to knit the example template, pandoc failed to find the google fonts (likely due to the pipes in betterposter.css; this issue is described [here](https://github.com/jgm/pandoc/issues/3629)). Replacing all pipes in the first line of betterposter.css with `%7C` fixes this issue:

`@import url('https://fonts.googleapis.com/css?family=Roboto%7CRoboto+Slab:700%7CSource+Code+Pro%7CSource+Sans+Pro:300,700');
`

Environment: RStudio (1.1.456), R (3.5.2), pandoc (1.19.2.1), rmarkdown (1.13), betterposter (0.0.1) running on Debian testing.

**Comment by gadenbuie** [comment]
Thanks for the report! I haven't used pandoc < 1.2 in a while ... does everything else work once you've made that change?

**Comment by jdforest** [comment]
Everything else seems to work; however, I am still trying to figure out how to change fonts, add background images and "hat" icons to the hero space, and adjust margins of the three areas in the rmd file.

**Comment by gadenbuie** [comment]
I opened an issue for improving the ability to change fonts. For now, you'll need to define override the CSS rules in [betterposter.css](https://github.com/GerkeLab/betterposter/blob/master/inst/resources/betterposter.css). 

To adjust the margins of the three areas, here are the IDs used for each of the sections.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5420529/59778536-abf7e880-9284-11e9-8758-ae654c751aac.png">

You can write css rules into your Rmd file directly, so to increase the padding (internal margins) of the right bar, you could add this to the top of your poster's Rmd.

````
```{css echo=FALSE}
#right-bar {
  padding: 10%;
}
```
````

In terms of "hat" icons, I'm not sure I understand but would be happy to help if you give a little more context.

**Comment by jdforest** [comment]
1) Thanks for the help on adjusting css parameters via the rmd file. This also allows folks to use a background image (with adjustable opacity) instead of a solid color:
```
/* Adjust space at top of #hero (center panel) */
#hero {
  padding-top: 33%;
  background-image: url("/path/to/image/my-image.jpg");
  background-color: rgba(255, 255, 255, 0.4);
  background-blend-mode: lighten;
}
```
Whether this is a good design philosophy or not can be debated, but it is at least a nice option to have.

2) If a background image is used, it would be nice to be able to adjust the background behind the hero text. Even if it is just a rectangle that can have its color and/or opacity adjusted.

3) Regarding the "hat" icon, it is just the capability of placing a (usually centered) image/icon above the hero text (this is demonstrated in the newest betterposter template). I can add the image in manually to the content area, but it is difficult to get the spacing right. It would be nice to have it float, centered above the text.
